# Generated by Django 3.0.1 on 2021-02-13 20:18

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20210213_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='atULcj', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
