# Generated by Django 3.0.1 on 2021-02-13 20:29

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20210213_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='HQnKQ4', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
