# Generated by Django 3.0.1 on 2021-02-13 23:37

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20210213_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='JVIfEq', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='access',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('staff', 'Staff'), ('admin', 'Admin')], default='read', max_length=255),
        ),
    ]
