# Generated by Django 3.0.1 on 2021-02-14 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0006_auto_20210213_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File'),
        ),
        migrations.AlterField(
            model_name='access',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='ehlR6w', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
