# Generated by Django 3.0.1 on 2021-02-14 01:08

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_auto_20210214_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='LyxUSy', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
