# Generated by Django 3.0.1 on 2021-02-14 01:58

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20210214_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='FTjaGO', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
