# Generated by Django 3.0.1 on 2021-02-14 02:01

from django.db import migrations
import file.models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20210214_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=file.models.get_uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
