# Generated by Django 3.0.1 on 2021-02-14 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_auto_20210214_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expiration',
            field=models.DurationField(default=datetime.timedelta(days=1), null=True),
        ),
    ]
