# Generated by Django 3.0.1 on 2020-07-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamepost",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gamepost",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gamepost",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
