language: python
python:
    # - "2.6"
    # - "2.7"
    # - "3.3"
    # - "3.4"
    # - "3.5"
    # - "3.6"
    - "3.7.7"
    - "3.7-dev"

# command to install dependencies
install: make init
test: make test

