alias mcd="mkcdir"
alias go="mkcdir"
alias dotfiles="cd $DOTFILES_PATH"
alias dotmain="v $DOTFILES_PATH/main.sh"
alias dotaliases="v $DOTFILES_PATH/aliases.sh"
alias dotfunctions="v $DOTFILES_PATH/functions.sh"
alias dotexports="v $DOTFILES_PATH/exports.sh"
alias dotzshenv="v $DOTFILES_PATH/.zshenv"
alias dota="dotaliases"
alias dotm="dotmain"
alias dotf="dotfunctions"
alias dote="dotexports"
alias dotz="dotzshenv"
alias esclave="cd ~/discordbot/esclave"
alias servant="cd ~/discordbot/servant-de-marc"
alias esclaveaws="ssh -i 'discordbotofmarcpartensky.pem' ubuntu@ec2-15-236-33-61.eu-west-3.compute.amazonaws.com"
alias mampstart='~/Library/Applications/MAMP/bin/start.sh'
alias mampstop='~/Library/Applications/MAMP/bin/stop.sh'
alias jsonbeautify="chrome https://jsonformatter.curiousconcept.com/"
alias github="chrome https://github.com/MarcPartensky/"
alias finder="open ."
alias py=python
alias activate="source venv/bin/activate"
alias py20='cd ~/programs/python/repository-2020'
alias pygames='cd ~/programs/python/repository-games'
alias pyml='cd ~/programs/python/machine-learning'
alias pyhome='cd ~/programs/python'
alias pypackages='cd /library/frameworks/python.framework/versions/3.8/lib/python3.8/site-packages/'
