version: "3.9"
x-common:
  website:
    &website
    DJANGO_SETTINGS_MODULE: django_project.settings
    SECRET_KEY: root
    FTP_URL: 0.0.0.0:21
  postgres:
    &postgres
    POSTGRES_NAME: website
    POSTGRESQL_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  redis:
    &redis
    REDIS_URL: redis:6379

services:
  website:
    environment:
      <<: *website
      <<: *postgres
      <<: *redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    working_dir: /app
    entrypoint: /app/entrypoint.sh
    depends_on:
      - redis
      - postgres
    networks:
      - website

  redis:
    image: redis
    environment:
      <<: *redis
    ports:
      - "6379:6379"
    networks:
      - website

  postgres:
    image: postgres
    environment:
      <<: *postgres
    ports:
      - "5432:5432"
    networks:
      - website

networks:
  website:
