version: "3.9"
services:
  website:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        env_file: .env
    ports:
      - "7000:7000"
      # - 443:443
      # - 21:10021
    # volumes:
    #   - .:.
    # links:
    #   - redis
    # networks:

  # redis:
  #   image: redis:alpine
