version: "3.9"
services:
  website:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        env_file: .env
    ports:
      - 443:443
      # - 21:10021
    # volumes:
    #   - .:.
    links:
      - redis
    # networks:

  redis:
    image: redis:alpine
