version: "3.9"
services:
  web:
    env_file: .env
    build: .
    ports:
      - 443:443
      # - 21:10021
    # volumes:
    #   - .:.
    links:
      - redis
    # networks:

  redis:
    image: redis:alpine
