version: "3.9"
services:
  website:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - 80:80
      # - 443:443
      - "8000:8000"
    working_dir: /app
    entrypoint: ./manage.py runserver 0.0.0.0:8000
    links:
      - redis
      - mysql

  redis:
    image: redis:latest
    # env_file: .env
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"
