version: "3.9"
x-common:
  website:
    &website
    DJANGO_SETTINGS_MODULE: django_project.settings
    SECRET_KEY: admin
    FTP_URL: 0.0.0.0:21
  postgres:
    &postgres
    POSTGRES_NAME: website
    POSTGRESQL_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  redis:
    &redis
    REDIS_URL: redis:6379

services:
  website:
    environment:
      <<: *website
      <<: *postgres
      <<: *redis
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    working_dir: /app
    entrypoint: /app/entrypoint.sh
    volumes:
      - "/app:$PWD"
    depends_on:
      - redis
      - postgres
    networks:
      - website

  postgres:
    image: postgres
    environment:
      <<: *postgres
    ports:
      - "5432:5432"
    networks:
      - website

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"

  redis:
    image: redis
    environment:
      <<: *redis
    ports:
      - "6379:6379"
    networks:
      - website

  rediscommander:
    image: rediscommander/redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: redis:6379
    ports:
    - "16379:8081"

networks:
  website:
