version: "3.9"
services:
  website:
    image: docker.io/marcpartensky/website:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - redis
      - postgres
    networks:
      - website

  redis:
    image: redis
    env_file:
      - .env
    networks:
      - website

  postgres:
    image: postgres
    env_file:
      - .env
    networks:
      - website

networks:
  website:
  postgres:
    external: true
