# Path variables
export PATH="$PATH:/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin"
export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:$PATH"
export PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:$PATH"
export PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
export PATH="/Users/marcpartensky/flutter/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/opt/local/bin:$PATH"
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

export CLICOLOR=1
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export TEST="This is a test"
export PRODUCTION=false
export DEBUG_VALUE="True"
export DEVELOPMENT=true
export WEBSITE_URL="https://marcpartensky.herokuapp.com"
export WEBSITE_USER="marcpartensky"
export WEBSITE_PASSWORD="glouaymay"
export ISEP_ID="mapa60217"
export ISEP_PORTAL_PASSWORD="fKY?Td7B"
export ISEP_HYPERPLANNING_PASSWORD="7SaxUGjq"
export APPLE_PASSWORD="MarcGPTL44"
export APPLE_MAIL="marc.partensky@gmail.com"
export GMAIL="marc.partensky@gmail.com"
export FREE_MAIL="marc.partensky@free.fr"
export HEROKU_PASSWORD_MARC_PARTENSKY_2="MarcGPTL44@heroku"
export AWS_ACCESS_KEY_ID="AKIAQWHDPXHAAQUJ6DNO"
export AWS_SECRET_ACCESS_KEY="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"
export AWS_STORAGE_BUCKET_NAME="django-blog-marc-partensky"
export SECRET_KEY="cdda0d3fff2c924abb9789bcf781e154449a794276d1e715"
export GOOGLE_APPLICATION_CREDENTIALS="/Users/marcpartensky/Google-Cloud/credentials.json"
export DISCORD_TOKEN="NzEwODYzNDIzMzA2NTk2MzU0.Xxg0uQ.wn54qCFTEPGcxzynmpE_zXIe2Yo"
export DISCORD_CLIENT_ID="710863423306596354"
export DISCORD_MONGO_CLUSTER="discord-cluster-5ckni.mongodb.net/test"
export DISCORD_MONGO_USERNAME="esclave"
export DISCORD_MONGO_PASSWORD="esclave"
export WOLFRAM_ALPHA_ID="WRG62L-Q5X5PUJQ83"
export FACEBOOK_MAIL="marc.partensky@free.fr"
export FACEBOOK_PASSWORD="glouaymayglouaymay69"
export FACEBOOK_MAIL_2="marc.partensky@gmail.com"
export FACEBOOK_PASSWORD_2="marcgptl44"
export FACEBOOK_MAIL_MISCORD="marc.partensky.website@gmail.com"
export FACEBOOK_PASSWORD_MISCORD="miscord@bot69"
export MISCORD_DASHBOARD_USERNAME="miscord-of-marc"
export MISCORD_DASHBOARD_PASSWORD="miscordofmarc"
export PYGITHUB_TOKEN="3a75f51f1b6d0f3dfd341c9e61c10ddaa2adc3f2"
export GITHUB_TOKEN="66c1fa3aeb514c830f9d7f99dee394790857cfaa"
export CAPTCHA_WEBSITE_KEY="6LenqaQZAAAAAC1KXdUOJC2OCZBEJ2DACeUVGEkl"
export CAPTCHA_SECRET_KEY="6LenqaQZAAAAAA_Y_Sx9i3Vh1q-TRSqZUUnmJzFV"
export LEEKWARS_USERNAME="Mazex"
export BRAWLSTARS_ID="8YC89YRL0"
export BRAWLSTARS_MAIL="marc.gptl44@gmail.com"
export BRAWLSTARS_PASSWORD="marc.partensky@brawlstars"
export BRAWLSTARS_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImQzY2EzNjMxLWIwZTAtNDA4NC05MGUwLTIyMDg5MmY2OTMwNiIsImlhdCI6MTU5MjUxNzE0NCwic3ViIjoiZGV2ZWxvcGVyLzdmYzlhMjM2LTVkMTMtMzgxNC1kYmJkLWUwYmU0YzFlOTdjMiIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiOTEuMTY1LjIxLjg3Il0sInR5cGUiOiJjbGllbnQifV19.EHXW9ji-11Av8p9oFBpQ02idYPGxapNKbFG6P6AprjlgkLLjZ1WN2VM7hkM2b9aPjJKbIlmE4BJEij5dvM-rfg"
export DISCORD_PREFIX="?"
export DISCORD_DEPLOYMENT="DEVELOPMENT"
export YTOPTS="-ciw -x --audio-format 'mp3' --audio-quality 0 -f bestaudio --embed-thumbnail -o '%(title    )s.%(ext)s' --rm-cache-dir"
export PP_PASSWORD="yaM-yauolG44"
export LS_COLORS="auto"

# export JAVA_HOME=$(/usr/libexec/java_home)
# For Pyenv
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"

# if command -v pyenv 1>/dev/null 2>&1; then
#  eval "$(pyenv init -)"
# fi
