# Generated by Django 3.1.7 on 2021-04-04 19:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file.models
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='files')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('public', models.BooleanField(default=True)),
                ('expiration', models.DurationField(default=datetime.timedelta(days=1), null=True)),
                ('path', models.FilePathField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('written', models.DateTimeField(auto_now=True)),
                ('read', models.DateTimeField(auto_now=True)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('write_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.DateTimeField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, default=file.models.get_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('staff', 'Staff'), ('admin', 'Admin')], default='read', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DurationField(default=datetime.timedelta(seconds=3600), null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('max_count', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
        ),
    ]
