# Generated by Django 3.1.7 on 2021-02-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210216_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.todo'),
        ),
    ]
