# Generated by Django 3.0.1 on 2020-11-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to='article/')),
                ('view_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('read_date', models.DateTimeField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
