# Generated by Django 3.0.1 on 2021-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210123_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiedmaillist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
