# Generated by Django 3.1.7 on 2021-03-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20201227_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='author',
        ),
        migrations.RemoveField(
            model_name='script',
            name='created',
        ),
        migrations.RemoveField(
            model_name='script',
            name='description',
        ),
        migrations.RemoveField(
            model_name='script',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='script',
            name='file',
        ),
        migrations.RemoveField(
            model_name='script',
            name='id',
        ),
        migrations.RemoveField(
            model_name='script',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='script',
            name='public',
        ),
        migrations.RemoveField(
            model_name='script',
            name='read',
        ),
        migrations.RemoveField(
            model_name='script',
            name='title',
        ),
        migrations.RemoveField(
            model_name='script',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='script',
            name='views',
        ),
        migrations.AddField(
            model_name='script',
            name='file_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='ran',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
