# Generated by Django 3.0.1 on 2021-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="state",
        ),
        migrations.AddField(
            model_name="todo",
            name="progress",
            field=models.FloatField(default=0),
        ),
    ]
