# Generated by Django 3.0.1 on 2021-02-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210125_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='dependencies',
            field=models.ManyToManyField(related_name='_todo_dependencies_+', to='todo.Todo'),
        ),
    ]
