# Generated by Django 4.0.4 on 2022-05-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210223_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dependencies',
            field=models.ManyToManyField(to='todo.todo'),
        ),
    ]
