# Generated by Django 3.2.23 on 2023-11-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dependencies',
            field=models.ManyToManyField(related_name='_todo_todo_dependencies_+', to='todo.Todo'),
        ),
    ]
