# Generated by Django 3.0.1 on 2021-02-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_preference_article_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/assets/img/default_avatar.svg', null=True, upload_to=''),
        ),
    ]
