# Generated by Django 3.0.1 on 2020-07-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200726_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='play',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
