name: Docker

on:
  push:
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
    - name: Install make
      run: sudo apt install make -y
    - name: Install Python3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - name: make init
      run: make init
    - name: make update
      run: make update
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: marcpartensky/website:latest
    - name: Compose up
      run: docker-compose -f dev.yml up -d website postgres mysql
    - name: Test
      run: docker-compse run test
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: marcpartensky/website:latest
