name: Docker

on:
  push:
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
    - name: Install Python3.7.7
      run: sudo apt install python3.7.7 -y
    - name: Clean apt
      run: |
        sudo apt-get clean autoclean &&
        sudo apt-get autoremove --yes &&
        sudo rm -rf /var/lib/{apt,dpkg,cache,log}/ &&
        sudo rm -rf /var/lib/apt/lists/*
    - name: Update pip
      run: pip install -U pip
    - name: Install pipenv
      run: pip install pipenv
    - name: Update pip dependencies
      run: pipenv lock --pre --clear
    - name: Install dependencies
      run: pipenv install
    - name: Export to requirements.txt
      run: pipenv lock -r > requirements.txt
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
