# Generated by Django 3.1.7 on 2021-05-17 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields
import url.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', shortuuidfield.fields.ShortUUIDField(blank=True, default=url.models.get_uuid, editable=False, max_length=22, unique=True)),
                ('target', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
