# Generated by Django 3.1.7 on 2021-05-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
