# Generated by Django 3.2.2 on 2021-05-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='count',
        ),
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
