# Generated by Django 3.2.2 on 2021-05-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_auto_20210521_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
